### PR TITLE
Fix Gem Version Issues and Update the Gem Bundle

### PR DESCRIPTION
**Pull request by conradbeach**
This branch fixes a couple of issues with gem versions.

Currently on `master`, you can't run `bundle install`. You'll get this error:
```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in
any of the sources listed in your Gemfile. If you haven't changed sources, that means
the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a
version other than mimemagic (0.3.5) that hasn't been removed in order to install.
```

`mimemagic` version `0.3.5` was yanked.

To address that, we could run `bundle update`, but `bundle update` also doesn't work because you get version conflicts.

```
Bundler could not find compatible versions for gem "graphql":
  In Gemfile:
    graphql (~> 1.9.18)

    graphql-batch (~> 0.3.9) was resolved to 0.3.10, which depends on
      graphql (< 2, >= 0.8)

    lms-graphql-api (>= 0.5.3) was resolved to 1.7.0, which depends on
      graphql (>= 1.8.2)

Bundler could not find compatible versions for gem "lms-api":
  In Gemfile:
    lms-api (~> 1.12.0)

    lms-graphql-api (>= 0.5.3) was resolved to 1.7.0, which depends on
      lms-api (>= 1.5.0)

Bundler could not find compatible versions for gem "pronto":
  In Gemfile:
    pronto

    pronto-eslint_npm was resolved to 0.7.1, which depends on
      pronto (~> 0.7.0)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 5.2.4.4)

    nuclear_secrets was resolved to 1.0.5, which depends on
      rails (>= 5.0.0)

Bundler could not find compatible versions for gem "rubocop":
  In Gemfile:
    rubocop (~> 0.88.0)

    rubocop-performance (~> 1.7.1) was resolved to 1.7.1, which depends on
      rubocop (>= 0.82.0)

    rubocop-rails (~> 2.7.1) was resolved to 2.7.1, which depends on
      rubocop (>= 0.87.0)
```

These version conflicts are a result of the `git` parameter that we added to the `pronto` gem in the `Gemfile`.

Removing the `git` parameter fixes the above version conflicts and allows you to run `bundle update` successfully. After running `bundle update`, you can successfully run `bundle install`.

### CODE REVIEW

**Comment by conradbeach** [comment]
Travis CI doesn't appear to be building anything for this PR. RSpec and JS tests are passing locally though.

**Comment by conradbeach** [comment]
Oh, I see. My branch isn't included in our configuration. Rude.

no_build_for_you

**Review by bfcoder — APPROVED** [review]
Looks good

**Comment by conradbeach** [comment]
@bfcoder Thanks!

**Pull request merged**
